# Generated by Django 5.2.16 on 2026-07-29 12:30

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_seed_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, validators=[contacts.models.validate_phone_format]),
        ),
    ]
